In [21]:
#import pandas for data frame operations

import pandas as pd

#import numpy for numerical operations

import numpy as np

#TASK 1

# create project data frame

project_data = {"ID":["A001","A002","A003","A004","A005","A002","A005","A003","A001","A003","A001","A004","A004","A005"],
    "Project":["Project 1","Project 2","Project 3","Project 4","Project 5","Project 6","Project 7","Project 8","Project 9","Project 10","Project 11","Project 12","Project 13","Project 14"],
    "Cost":[1002000,2000000,4500000,5500000,None,680000,400000,350000,None,300000,2000000,1000000,3000000,200000],
    "Status":["Finished","Ongoing","Finished","Ongoing","Finished","Failed","Finished","Failed","Ongoing","Finished","Failed","Ongoing","Finished","Finished"]}
project_df = pd.DataFrame(project_data)

# save to csv

project_df.to_csv("project.csv", index = False)

project_df

      ID     Project       Cost    Status
0   A001   Project 1  1002000.0  Finished
1   A002   Project 2  2000000.0   Ongoing
2   A003   Project 3  4500000.0  Finished
3   A004   Project 4  5500000.0   Ongoing
4   A005   Project 5        NaN  Finished
5   A002   Project 6   680000.0    Failed
6   A005   Project 7   400000.0  Finished
7   A003   Project 8   350000.0    Failed
8   A001   Project 9        NaN   Ongoing
9   A003  Project 10   300000.0  Finished
10  A001  Project 11  2000000.0    Failed
11  A004  Project 12  1000000.0   Ongoing
12  A004  Project 13  3000000.0  Finished
13  A005  Project 14   200000.0  Finished

In [22]:
# create employee data frame

employee_data = {"ID":["A001","A002","A003","A004","A005"],
                 "Name":["John Alter","Alice Luxumberg","Tom Sabestine","Nina Adgra","Amy Johny"],
                 "Gender":["M","F","M","F","F"],
                 "City":["Paris","London","Berlin","Newyork","Madrid"],
                 "Age":[25,27,29,31,30]}  
employee_df = pd.DataFrame(employee_data)

# save to csv

employee_df.to_csv("employee.csv", index = False)

employee_df

     ID             Name Gender     City  Age
0  A001       John Alter      M    Paris   25
1  A002  Alice Luxumberg      F   London   27
2  A003    Tom Sabestine      M   Berlin   29
3  A004       Nina Adgra      F  Newyork   31
4  A005        Amy Johny      F   Madrid   30

In [23]:
# Create seniority level data frame

seniority_level_data = {"ID":["A001","A002","A003","A004","A005"],
                        "Designation Level":[2,2,3,2,3]}
seniority_df = pd.DataFrame(seniority_level_data)

# save to csv

seniority_df.to_csv("seniority.csv", index = False)

seniority_df

     ID  Designation Level
0  A001                  2
1  A002                  2
2  A003                  3
3  A004                  2
4  A005                  3

In [24]:
# TASK 2

# Load Project DataFrame

project_df = pd.read_csv("project.csv")

# convert cost column to list of iteration

costs = project_df["Cost"].tolist()

# loop through costs

for i in range(len(costs)):
    if costs[i] is None or (isinstance(costs[i], float) and np.isnan(costs[i])):
        prev_values = [c for c in costs[:i] if c is not None]
        costs[i] = sum(prev_values)/len(prev_values)
project_df.loc[:,"Cost"]=costs

project_df

      ID     Project       Cost    Status
0   A001   Project 1  1002000.0  Finished
1   A002   Project 2  2000000.0   Ongoing
2   A003   Project 3  4500000.0  Finished
3   A004   Project 4  5500000.0   Ongoing
4   A005   Project 5  3250500.0  Finished
5   A002   Project 6   680000.0    Failed
6   A005   Project 7   400000.0  Finished
7   A003   Project 8   350000.0    Failed
8   A001   Project 9  2210312.5   Ongoing
9   A003  Project 10   300000.0  Finished
10  A001  Project 11  2000000.0    Failed
11  A004  Project 12  1000000.0   Ongoing
12  A004  Project 13  3000000.0  Finished
13  A005  Project 14   200000.0  Finished

In [25]:
# TASK 3

# Load employee data frame

employee = pd.read_csv("employee.csv")

# split name column

employee_df[["First name","Last name"]] = employee_df["Name"].str.split(" ", n=1, expand=True)

# Drop old name column

employee_df = employee_df.drop(columns=["Name"])

# desired order

employee_df = employee_df[["ID","First name", "Last name","Gender","City","Age"]]

employee_df

     ID First name  Last name Gender     City  Age
0  A001       John      Alter      M    Paris   25
1  A002      Alice  Luxumberg      F   London   27
2  A003        Tom  Sabestine      M   Berlin   29
3  A004       Nina      Adgra      F  Newyork   31
4  A005        Amy      Johny      F   Madrid   30

In [26]:
# TASK 4

# load seniority dataframe

seniority_df = pd.read_csv("seniority.csv")

# merge project and employee dataframe

merged = pd.merge(project_df,employee_df, on="ID")

# meerge with seniority dataframe

Final = pd.merge(merged,seniority_df, on="ID")

Final

,ID,Project,Cost,Status,First name,Last name,Gender,City,Age,Designation Level
0,A001,Project 1,1002000.0,Finished,John,Alter,M,Paris,25,2
1,A002,Project 2,2000000.0,Ongoing,Alice,Luxumberg,F,London,27,2
2,A003,Project 3,4500000.0,Finished,Tom,Sabestine,M,Berlin,29,3
3,A004,Project 4,5500000.0,Ongoing,Nina,Adgra,F,Newyork,31,2
4,A005,Project 5,3250500.0,Finished,Amy,Johny,F,Madrid,30,3
5,A002,Project 6,680000.0,Failed,Alice,Luxumberg,F,London,27,2
6,A005,Project 7,400000.0,Finished,Amy,Johny,F,Madrid,30,3
7,A003,Project 8,350000.0,Failed,Tom,Sabestine,M,Berlin,29,3
8,A001,Project 9,2210312.5,Ongoing,John,Alter,M,Paris,25,2
9,A003,Project 10,300000.0,Finished,Tom,Sabestine,M,Berlin,29,3
10,A001,Project 11,2000000.0,Failed,John,Alter,M,Paris,25,2
11,A004,Project 12,1000000.0,Ongoing,Nina,Adgra,F,Newyork,31,2
12,A004,Project 13,3000000.0,Finished,Nina,Adgra,F,Newyork,31,2
13,A005,Project 14,200000.0,Finished,Amy,Johny,F,Madrid,30,3

In [27]:
# Task 5

# Add Bonus column: 5% of Cost if Status is Finished, else 0

Final["Bonus"] = np.where(Final["Status"]=="Finished", Final["Cost"]*0.05,0)

Final

,ID,Project,Cost,Status,First name,Last name,Gender,City,Age,Designation Level,Bonus
0,A001,Project 1,1002000.0,Finished,John,Alter,M,Paris,25,2,50100.0
1,A002,Project 2,2000000.0,Ongoing,Alice,Luxumberg,F,London,27,2,0.0
2,A003,Project 3,4500000.0,Finished,Tom,Sabestine,M,Berlin,29,3,225000.0
3,A004,Project 4,5500000.0,Ongoing,Nina,Adgra,F,Newyork,31,2,0.0
4,A005,Project 5,3250500.0,Finished,Amy,Johny,F,Madrid,30,3,162525.0
5,A002,Project 6,680000.0,Failed,Alice,Luxumberg,F,London,27,2,0.0
6,A005,Project 7,400000.0,Finished,Amy,Johny,F,Madrid,30,3,20000.0
7,A003,Project 8,350000.0,Failed,Tom,Sabestine,M,Berlin,29,3,0.0
8,A001,Project 9,2210312.5,Ongoing,John,Alter,M,Paris,25,2,0.0
9,A003,Project 10,300000.0,Finished,Tom,Sabestine,M,Berlin,29,3,15000.0
10,A001,Project 11,2000000.0,Failed,John,Alter,M,Paris,25,2,0.0
11,A004,Project 12,1000000.0,Ongoing,Nina,Adgra,F,Newyork,31,2,0.0
12,A004,Project 13,3000000.0,Finished,Nina,Adgra,F,Newyork,31,2,150000.0
13,A005,Project 14,200000.0,Finished,Amy,Johny,F,Madrid,30,3,10000.0

In [28]:
# Task 6

# Demote designation level by 1 if project failed

Final.loc[Final["Status"] == "Failed", "Designation Level"]+=1

# Drop employees whose designation level > 4 (ineligible to lead projects)

Final = Final[Final["Designation Level"]<=4]

Final

,ID,Project,Cost,Status,First name,Last name,Gender,City,Age,Designation Level,Bonus
0,A001,Project 1,1002000.0,Finished,John,Alter,M,Paris,25,2,50100.0
1,A002,Project 2,2000000.0,Ongoing,Alice,Luxumberg,F,London,27,2,0.0
2,A003,Project 3,4500000.0,Finished,Tom,Sabestine,M,Berlin,29,3,225000.0
3,A004,Project 4,5500000.0,Ongoing,Nina,Adgra,F,Newyork,31,2,0.0
4,A005,Project 5,3250500.0,Finished,Amy,Johny,F,Madrid,30,3,162525.0
5,A002,Project 6,680000.0,Failed,Alice,Luxumberg,F,London,27,3,0.0
6,A005,Project 7,400000.0,Finished,Amy,Johny,F,Madrid,30,3,20000.0
7,A003,Project 8,350000.0,Failed,Tom,Sabestine,M,Berlin,29,4,0.0
8,A001,Project 9,2210312.5,Ongoing,John,Alter,M,Paris,25,2,0.0
9,A003,Project 10,300000.0,Finished,Tom,Sabestine,M,Berlin,29,3,15000.0
10,A001,Project 11,2000000.0,Failed,John,Alter,M,Paris,25,3,0.0
11,A004,Project 12,1000000.0,Ongoing,Nina,Adgra,F,Newyork,31,2,0.0
12,A004,Project 13,3000000.0,Finished,Nina,Adgra,F,Newyork,31,2,150000.0
13,A005,Project 14,200000.0,Finished,Amy,Johny,F,Madrid,30,3,10000.0

In [29]:
# Task 7

# Add Mr. or Mrs. prefix based on Gender

Final["First name"] = np.where(Final["Gender"]=="M","Mr. "+Final["First name"], "Mrs. "+Final["First name"])

# Drop Gender column since prefix replaces it

Final.drop(columns=["Gender"], inplace=True)

Final

,ID,Project,Cost,Status,First name,Last name,City,Age,Designation Level,Bonus
0,A001,Project 1,1002000.0,Finished,Mr. John,Alter,Paris,25,2,50100.0
1,A002,Project 2,2000000.0,Ongoing,Mrs. Alice,Luxumberg,London,27,2,0.0
2,A003,Project 3,4500000.0,Finished,Mr. Tom,Sabestine,Berlin,29,3,225000.0
3,A004,Project 4,5500000.0,Ongoing,Mrs. Nina,Adgra,Newyork,31,2,0.0
4,A005,Project 5,3250500.0,Finished,Mrs. Amy,Johny,Madrid,30,3,162525.0
5,A002,Project 6,680000.0,Failed,Mrs. Alice,Luxumberg,London,27,3,0.0
6,A005,Project 7,400000.0,Finished,Mrs. Amy,Johny,Madrid,30,3,20000.0
7,A003,Project 8,350000.0,Failed,Mr. Tom,Sabestine,Berlin,29,4,0.0
8,A001,Project 9,2210312.5,Ongoing,Mr. John,Alter,Paris,25,2,0.0
9,A003,Project 10,300000.0,Finished,Mr. Tom,Sabestine,Berlin,29,3,15000.0
10,A001,Project 11,2000000.0,Failed,Mr. John,Alter,Paris,25,3,0.0
11,A004,Project 12,1000000.0,Ongoing,Mrs. Nina,Adgra,Newyork,31,2,0.0
12,A004,Project 13,3000000.0,Finished,Mrs. Nina,Adgra,Newyork,31,2,150000.0
13,A005,Project 14,200000.0,Finished,Mrs. Amy,Johny,Madrid,30,3,10000.0

In [30]:
# Task 8

# Promote designation level by 1 for the employees age > 29

for i in range (len(Final)):
    if Final.loc[i,"Age"]>29:
        Final.loc[i,"Designation Level"]-=1

Final

,ID,Project,Cost,Status,First name,Last name,City,Age,Designation Level,Bonus
0,A001,Project 1,1002000.0,Finished,Mr. John,Alter,Paris,25,2,50100.0
1,A002,Project 2,2000000.0,Ongoing,Mrs. Alice,Luxumberg,London,27,2,0.0
2,A003,Project 3,4500000.0,Finished,Mr. Tom,Sabestine,Berlin,29,3,225000.0
3,A004,Project 4,5500000.0,Ongoing,Mrs. Nina,Adgra,Newyork,31,1,0.0
4,A005,Project 5,3250500.0,Finished,Mrs. Amy,Johny,Madrid,30,2,162525.0
5,A002,Project 6,680000.0,Failed,Mrs. Alice,Luxumberg,London,27,3,0.0
6,A005,Project 7,400000.0,Finished,Mrs. Amy,Johny,Madrid,30,2,20000.0
7,A003,Project 8,350000.0,Failed,Mr. Tom,Sabestine,Berlin,29,4,0.0
8,A001,Project 9,2210312.5,Ongoing,Mr. John,Alter,Paris,25,2,0.0
9,A003,Project 10,300000.0,Finished,Mr. Tom,Sabestine,Berlin,29,3,15000.0
10,A001,Project 11,2000000.0,Failed,Mr. John,Alter,Paris,25,3,0.0
11,A004,Project 12,1000000.0,Ongoing,Mrs. Nina,Adgra,Newyork,31,1,0.0
12,A004,Project 13,3000000.0,Finished,Mrs. Nina,Adgra,Newyork,31,1,150000.0
13,A005,Project 14,200000.0,Finished,Mrs. Amy,Johny,Madrid,30,2,10000.0

In [31]:
# Task 9

# group by ID and first name, sum project costs

total_proj_cost = Final.groupby(["ID","First name"])["Cost"].sum().reset_index()

# rename columns cost to total cost

total_proj_cost.rename(columns={"Cost":"Total Cost"}, inplace=True)

# save as csv

total_proj_cost.to_csv("TotalProjCost.csv", index=False)

total_proj_cost

     ID  First name  Total Cost
0  A001    Mr. John   5212312.5
1  A002  Mrs. Alice   2680000.0
2  A003     Mr. Tom   5150000.0
3  A004   Mrs. Nina   9500000.0
4  A005    Mrs. Amy   3850500.0

In [32]:
# Task 10

# filter employee details whose city name contains 'o'

Result= employee_df[employee_df["City"].str.contains('o', case=False)]

Result

     ID First name  Last name Gender     City  Age
1  A002      Alice  Luxumberg      F   London   27
3  A004       Nina      Adgra      F  Newyork   31